apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dev-app
type: Opaque
data:
  # username: root (base64)
  username: cm9vdA==
  # password: mypassword (base64)
  password: bXlwYXNzd29yZA==
  # DB_USER: root (base64)
  DB_USER: cm9vdA==
  # DB_PASSWORD: mypassword (base64)
  DB_PASSWORD: bXlwYXNzd29yZA==
